FROM tommylau/lnmpa:apache

MAINTAINER Tommy Lau <tommy@gen-new.com>

# Setup the Xdebug version to install
ENV XDEBUG_VERSION 2.2.6
ENV XDEBUG_MD5 f216356861e27284580d0208060ea7fa

# Install Xdebug
RUN set -x \
	&& curl -SL "http://www.xdebug.org/files/xdebug-$XDEBUG_VERSION.tgz" -o xdebug.tgz \
	&& echo $XDEBUG_MD5 xdebug.tgz | md5sum -c - \
	&& mkdir -p /usr/src/xdebug \
	&& tar -xf xdebug.tgz -C /usr/src/xdebug --strip-components=1 \
	&& rm xdebug.* \
	&& cd /usr/src/xdebug \
	&& phpize \
	&& ./configure \
	&& make -j"$(nproc)" \
	&& make install \
	&& make clean

COPY ext-xdebug.ini /usr/local/etc/php/conf.d/

